# iroshan

version: '3.8'
services:
  mongodb:
    image:  mongo:latest
    container_name: mongodb
    restart:  unless-stopped
    env_file:
      - variables.env
    ports:
      - 27017:27017


# docker exec <name_of_container> env
# list all the env details in the container