# iroshan vidanage
# assignment docker-compose drupal

services:

  drupal: # drupal service
    image: drupal:latest
    ports:
      - '8080:80' # port is running on 80
    volumes:
      - drupal:/var/www/html
  
  postgres:
    image: postgres:latest
    environment: # can use environment or -env to pass the env variables
      - POSTGRES_PASSWORD=mypasswd

volumes: # need to create the volumes
  drupal:
