## Docker compose challenge

version: "1.8"
services:
 app:
 image: my:latest
 container_name: app
 restart: always
 ports:
 - "8080:80"
 environment:
 - DB_HOST=db
 - DB_USER=root
 - DB_PASSWORD=secret
 depends_on:
 - db
 db:
 image: mysql:5.7
 container_name: db
 restart: always
 environment:
 MYSQL_ROOT_PASSWORD: secret
 MYSQL_DATABASE: app_db
 volumes:
 - db_data:/var/lib/mysql

 nginx:
 image: nginx:latest
 container_name: nginx
 restart: always
 ports:
 - "80:80"
 volumes:
 - ./nginx.conf:/etc/nginx/nginx.conf:ro
 depends_on:
 - My_app

volumes:
 db_data:

Network:
 - App
