# you should use the `node` official image, with the alpine 6.x branch (`node:6-alpine`)
FROM node:6-alpine
# Yes this is a 2-year old image of node, but all official images are always available on Docker Hub forever,
# to ensure even old apps still work. It is common to still need to deploy old app versions, even years later.

# This app listens on port 3000, but the container should listen on port 80 of the Docker host, so it will respond to [http://localhost:80](http://localhost:80) on your computer
EXPOSE 3000

# Then it should use the alpine package manager to install tini: `apk add --no-cache tini`.
RUN apk add --no-cache tini

# Then it should create directory /usr/src/app for app files with `mkdir -p /usr/src/app`, or with the Dockerfile command `WORKDIR /usr/src/app`.
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# ARG CONTEXT_PATH
# Get path from build command
# /home/iroshanav/Documents/Repos/udemy-docker-mastery/dockerfile-assignment-1

# Node.js uses a "package manager", so it needs to copy in package.json file.
COPY package.json pachage.json


# docker build --no-cache -t test-node --build-arg CONTEXT_PATH="$(cat /home/iroshanav/Documents/Repos/udemy-docker-mastery/dockerfile-assignment-1/package.json)" -f Dockerfile-practice-assignment .
# RUN echo "${CONTEXT_PATH}" > package.json

# Then it needs to run 'npm install' to install dependencies from that file.
# To keep it clean and small, run `npm cache clean --force` after the above, in the same RUN command.
RUN npm install && npm cache clean --force

# Then it needs to copy in all files from current directory into the image.
COPY . .

# Then it needs to start the container with the command `/sbin/tini -- node ./bin/www`. Be sure to use JSON array syntax for CMD. (`CMD [ "something", "something" ]`)
CMD ["/sbin/tini", "--", "node", "./bin/www"]

# In the end you should be using FROM, RUN, WORKDIR, COPY, EXPOSE, and CMD commands